/*******************************************************************
// Copyright (c) 2002, 2003, 2004, 2005, 
// Robert Umbehant
// mailto:rumbehant@wheresjames.com
//
// This program is free software; you can redistribute it and/or 
// modify it under the terms of the GNU General Public License as 
// published by the Free Software Foundation; either version 2 of 
// the License, or (at your option) any later version.

// This program is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public 
// License along with this program; if not, write to the Free 
// Software Foundation, Inc., 59 Temple Place, Suite 330, 
// Boston, MA 02111-1307 USA
//
*******************************************************************/
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vp.rc
//
#define IDC_PLEASEHELP                  3
#define IDC_BACK                        3
#define IDC_APPLY                       4
#define IDC_HELPBTN                     4
#define IDD_ABOUTBOX                    100
#define CG_IDD_PUBIMGVIEW               101
#define CG_ID_VIEW_PUBIMGVIEW           102
#define CG_IDD_IMAGE                    103
#define CG_IDD_SERVER                   104
#define IDB_LIGHTBULB                   105
#define CG_ID_VIEW_IMAGE                106
#define IDD_TIP                         107
#define CG_IDS_DIDYOUKNOW               108
#define IDR_MAINFRAME                   128
#define IDR_VPTYPE                      129
#define IDD_CHOOSEDRIVER                130
#define IDP_DATE                        131
#define IDI_DRIVE_REMOVEABLE            131
#define IDM_TRAYMENU                    132
#define IDD_WZ_WELCOME                  132
#define IDP_IMAGE                       133
#define IDD_REGBROWSER                  133
#define IDP_WATERMARK                   134
#define IDI_DIR_CLOSED                  134
#define IDP_RECT                        135
#define IDI_DIR_OPEN                    135
#define IDM_IMGMENU                     135
#define IDP_TIME                        136
#define IDI_DRIVE_FIXED                 136
#define IDD_IMGVIEW                     136
#define IDD_WZ_FRAME                    137
#define IDI_BACK                        137
#define IDP_TEXT                        138
#define IDI_DRIVE_CDROM                 138
#define IDI_TEXT                        139
#define IDI_ZOOMOUT                     140
#define IDI_DRIVE_UNKNOWN               141
#define IDI_DRIVE_NO_ROOT_DIR           142
#define IDI_DRIVE_RAMDISK               143
#define IDI_ROTATELEFT                  144
#define IDI_FX                          145
#define IDD_UPLOAD                      146
#define IDR_MENU2                       146
#define IDD_PROP                        149
#define IDI_FULLSIZE                    149
#define IDD_PROPBAR                     150
#define IDI_LIGHTEN                     151
#define IDI_DARKEN                      153
#define IDD_EDITPARAM                   155
#define IDI_COLOR                       156
#define IDI_BLOCKS                      163
#define IDD_WZ_CAM                      179
#define IDI_CAMERA2                     184
#define IDI_FRAME                       190
#define IDI_FTP                         192
#define IDI_BLUEDISK                    193
#define IDH_ADMIN                       194
#define IDH_PWD                         195
#define IDD_MOTION                      196
#define IDI_MOTION                      197
#define IDD_PG_BCKIMG                   198
#define IDD_PG_IMAGEPROP                199
#define IDD_NEWPUBIMG                   200
#define IDI_TIME                        201
#define IDD_PUBTHUMBNAIL                201
#define IDT_INSERT                      202
#define IDD_LOGFILES                    202
#define IDI_DATE                        203
#define IDD_CGI                         203
#define IDI_RECT                        204
#define IDI_IMAGE                       205
#define IDI_WATERMARK                   206
#define IDI_ICON1                       207
#define IDI_CGI                         207
#define IDI_VIDEO                       208
#define IDD_ADDCGI                      208
#define IDP_VIDEO                       209
#define IDI_FONT                        209
#define IDD_PROPERTIES                  210
#define IDW_ALARM                       210
#define IDD_HTMLBUILD                   211
#define IDD_HTMLPUBLISH                 213
#define IDD_PG_CHROMAKEY                214
#define IDD_PG_CHROMABCK                215
#define IDI_TICK_RIGHT                  216
#define IDD_MESSAGEVIEW                 216
#define IDI_TICK_LEFT                   217
#define IDI_TICK_UP                     218
#define IDI_TICK_DOWN                   219
#define IDI_DS_TICK_RIGHT               220
#define IDI_DS_TICK_LEFT                221
#define IDI_DS_TICK_UP                  222
#define IDI_DS_TICK_DOWN                223
#define IDI_SETUPWIZARD                 224
#define IDI_WAND                        225
#define IDD_WZ_PUBTYPE                  226
#define IDD_WZ_LOCALSERVER              227
#define IDD_WZ_FTP                      228
#define IDD_PAGEFRAME                   229
#define IDM_IMAGELIST                   230
#define IDD_SIMPLE                      231
#define IDD_PG_MASK                     232
#define IDI_GEARS                       233
#define IDI_X                           234
#define IDI_WHITEKNIGHT                 235
#define IDI_PRINTER                     236
#define IDI_SERVERUPLOAD                237
#define IDI_SAVEDISK                    238
#define IDI_LARGEGEARS                  239
#define IDI_LARGEWHITEKNIGHT            240
#define IDI_WEB                         241
#define IDD_SIMPLESETTINGS              242
#define IDI_CAMERA                      243
#define IDI_LARGEWRENCH                 244
#define IDI_XPCLOSE                     245
#define IDD_CHAT                        247
#define IDI_CHAT                        248
#define IDI_USERS                       249
#define IDD_PG_VIDEO                    250
#define IDR_SHUTDOWN                    251
#define IDD_PUBSOUNDS                   251
#define IDD_PG_DRAWINGORDER             252
#define IDD_PG_TEXT                     253
#define IDW_CAMERA                      253
#define IDD_PG_TEXTFLAGS                254
#define IDD_PG_TIME                     255
#define IDD_PG_DATE                     256
#define IDM_POPUP                       257
#define IDD_PG_URL                      257
#define IDD_SERVER                      258
#define IDI_REFRESH                     258
#define IDD_PG_RECT                     259
#define IDD_WZFTP_FRAME                 260
#define IDD_FTPLIST                     261
#define IDD_WZFTP_PG2                   262
#define IDD_WZFTP_PG1                   263
#define IDD_EMAILLIST                   265
#define IDD_WZEMAIL_PG1                 266
#define IDD_WZEMAIL_PG2                 267
#define IDD_WZ_SAVE                     268
#define IDD_WZ_EMAILINFO                269
#define IDI_TIP                         270
#define IDI_HELP                        271
#define IDI_SMALL_CAMERA                272
#define IDI_TOOLBAR                     273
#define IDD_MESSAGEBOX                  274
#define IDD_MAINTOOLBAR                 275
#define IDI_NEWIMAGEWIZARD              276
#define IDI_PUBLISHING                  277
#define IDI_GREENREFRESH                278
#define IDI_PROPERTIES                  279
#define IDI_SMALL_BLOCKS                280
#define IDI_SMALL_CAMERA_SETTINGS       281
#define IDI_ABOUT                       282
#define IDD_OVERLAYTOOLBAR              283
#define IDI_OV_TEXT                     284
#define IDI_OV_SPECIALTEXT              285
#define IDI_OV_RECT                     286
#define IDI_OV_TIME                     287
#define IDI_OV_DATE                     288
#define IDI_OV_IMAGE                    289
#define IDI_OV_WATERMARK                290
#define IDI_OV_VIDEO                    291
#define IDI_OV_URL                      292
#define IDI_OV_SCREENSHOT               293
#define IDI_SMALL_USERS                 294
#define IDI_EYEBALL                     295
#define IDI_EYELOOK                     296
#define IDD_PUBEXTRA                    297
#define IDD_VIDEOSETTINGS               298
#define IDI_RECORD                      299
#define IDD_PG_IMAGE                    300
#define IDI_PINOUT                      300
#define IDI_LIGHTBULB                   301
#define IDD_PG_TRANS                    302
#define IDI_PININ                       302
#define IDD_SETTINGS                    303
#define IDI_SUNKENDISK                  303
#define IDD_SERVERMAP                   304
#define IDI_BLANK                       304
#define IDD_SERVERLOG                   305
#define IDI_EYELOOK2                    305
#define IDI_SERVER                      306
#define IDD_LOGTARGET                   306
#define IDI_WRENCH                      307
#define IDI_FILE                        308
#define IDI_FOLDER                      309
#define IDI_TV_GREEN                    310
#define IDR_LICENSE                     311
#define IDI_TV_RED                      312
#define IDI_TV_BLUE                     313
#define IDD_MAPIMAGE                    314
#define IDI_BULB                        314
#define IDD_MAPFOLDER                   315
#define IDP_SCREENSHOT                  316
#define IDI_SMALLBULB                   317
#define IDP_URL                         318
#define IDP_STEXT                       319
#define IDD_INFORM                      350
#define IDD_GENERAL                     351
#define IDI_BARCODE                     352
#define IDD_PG_STEXT                    353
#define IDD_PG_SCREENSHOT               354
#define IDR_TIPS                        355
#define IDI_SPRINT                      356
#define IDI_URL                         357
#define IDI_SCREENSHOT                  358
#define IDI_STEXT                       359
#define IDD_FTP                         360
#define IDD_PUBLISHING                  361
#define IDI_LETTER                      362
#define IDI_SMALL_LETTER                363
#define IDI_DISK                        364
#define IDD_PUBWHAT                     365
#define IDD_PUBWHERE                    366
#define IDD_PUBFRAME                    367
#define IDI_WORLD                       368
#define IDD_PUBWHEN                     369
#define IDD_PUBHOW                      400
#define IDI_WINDOWS                     401
#define IDD_ONCLOSE                     402
#define IDI_CLOSE                       403
#define IDI_MINIMIZE                    404
#define IDD_IMGFXEDITOR                 405
#define IDD_EMAILSETTINGS               406
#define IDI_LETTER1                     407
#define IDD_EDITPARAMS                  408
#define IDI_MIRROR                      409
#define IDI_FLIP                        410
#define IDI_GRAYSCALE                   411
#define IDI_ROTATE                      412
#define IDI_NEGATIVE                    440
#define IDI_RESAMPLE                    441
#define IDI_DITHER                      442
#define IDI_CROP                        443
#define IDI_NOISE                       444
#define IDI_MEDIAN                      445
#define IDI_GAMMA                       446
#define IDI_SHIFT                       447
#define IDI_THRESHOLD                   448
#define IDI_UPLOAD                      449
#define IDI_COLORIZE                    450
#define IDI_LIGHT                       451
#define IDI_ERODE                       452
#define IDI_DILATE                      453
#define IDD_SPLASH                      454
#define IDI_DRIVE_REMOTE                454
#define IDD_PURCHASE                    455
#define IDI_FILE1                       455
#define IDR_SPLASH                      456
#define IDI_SMALLFRAME                  456
#define IDD_UPDATECHECK                 457
#define IDI_CHECK                       457
#define IDD_COMPOSEMAIL                 458
#define IDI_UNCHECK                     458
#define IDD_REGISTER                    459
#define IDI_NEXT                        459
#define IDD_JPGSETTINGS                 460
#define IDI_ROTATERIGHT                 460
#define IDI_ZOOMIN                      461
#define IDC_NAME                        1000
#define IDC_BLANK                       1001
#define IDC_ADDR                        1001
#define IDC_MV_LIST                     1001
#define IDC_STARTUP                     1002
#define IDC_MV_TEXT                     1002
#define IDC_BCKTYPE2                    1003
#define IDC_NEXTTIP                     1004
#define IDC_VIDEO                       1005
#define IDC_USER                        1006
#define IDC_BCKTYPE3                    1007
#define IDC_WEB                         1007
#define IDC_TIPSTRING                   1008
#define IDC_CHOOSE_IMAGE                1009
#define IDC_DRIVERS                     1011
#define IDC_IMAGE                       1012
#define IDC_COMBO                       1012
#define IDC_NEXT                        1013
#define IDC_IMAGEFILE                   1013
#define IDC_BCKTYPE                     1014
#define IDC_DEFAULTS                    1014
#define IDC_TITLE                       1015
#define IDC_CUSTOMSIZE                  1016
#define IDC_WIDTH                       1017
#define IDC_TAB                         1018
#define IDC_HEIGHT                      1019
#define IDC_AUTOSIZE                    1020
#define IDC_LIST                        1021
#define IDC_MOVEUP                      1022
#define IDC_SETTINGS                    1023
#define IDC_LIST2                       1024
#define IDC_MAPLIST                     1025
#define IDC_FORMAT                      1026
#define IDC_MOVEDOWN                    1027
#define IDC_STATUSBOX                   1027
#define IDC_ENABLE                      1028
#define IDC_LOGIN                       1028
#define IDC_MV_POPUP                    1028
#define IDC_FORMAT2                     1029
#define IDC_NOSMOOTHING                 1029
#define IDC_MV_POPUPWARNINGS            1029
#define IDC_DISABLE                     1030
#define IDC_GMT                         1031
#define IDC_USERS                       1032
#define IDC_GMT2                        1033
#define IDC_USERS2                      1034
#define IDC_HITS                        1035
#define IDC_SEP                         1036
#define IDC_STYLE                       1037
#define IDC_RUN                         1038
#define IDC_STYLE2                      1039
#define IDC_COLOR                       1040
#define IDC_PORT                        1041
#define IDC_LOCALADDRESS                1042
#define IDC_STYLE3                      1043
#define IDC_FILENAME                    1044
#define IDC_MAXUSERS                    1045
#define IDC_REMOTEADDRESS               1046
#define IDC_CHOOSE_FILENAME             1047
#define IDC_TRANSPARENCY                1048
#define IDC_REMOVEDIR                   1049
#define IDC_REMOVEIMG                   1060
#define IDC_CHOOSE_COLOR                1061
#define IDC_ADDDIR                      1062
#define IDC_CHOOSE_MASKCOLOR            1062
#define IDC_ADDIMG                      1063
#define IDC_TRANSLUCENCY                1064
#define IDC_REMOVEDIR2                  1065
#define IDC_REMOVEMAP                   1066
#define IDC_EMAILMSG                    1066
#define IDC_ADDDIR2                     1067
#define IDC_PSIZETEXT                   1067
#define IDC_LOGFILE                     1068
#define IDC_SIZETEXT                    1068
#define IDC_ADDMAP                      1069
#define IDC_PATH                        1069
#define IDC_SLIDEPOSITIVE               1070
#define IDC_CHOOSE_PATH                 1070
#define IDC_CHOOSE_LOG                  1071
#define IDC_TFNAME                      1071
#define IDC_PURCHASE                    1072
#define IDC_TFNAME_TEXT                 1072
#define IDC_REGISTER                    1072
#define IDC_POSITIVE                    1073
#define IDC_HTTP_PASSWORD_TXT           1073
#define IDC_CHECK1                      1074
#define IDC_SYNCTOCLOCK                 1074
#define IDC_ENABLEHTTP                  1074
#define IDC_ENABLE_OVERLAY              1074
#define IDC_MASK                        1074
#define IDC_SAVE                        1074
#define IDC_ENABLESOUND                 1074
#define IDC_ENABLECHAT                  1074
#define IDC_FRAMEAVG                    1074
#define IDC_COMPRESS                    1074
#define IDC_REMOTE                      1075
#define IDC_SMTP                        1075
#define IDC_ENABLE_BACKGROUND           1075
#define IDC_BORDER                      1076
#define IDC_PAGE_NAME_TXT               1076
#define IDC_ASPECT                      1077
#define IDC_REMOTE_PASSWORD_TXT         1077
#define IDC_PASSIVE                     1078
#define IDC_DRIVER                      1078
#define IDC_SLIDEQUALITY                1078
#define IDC_ROTATE                      1079
#define IDC_SCANTYPE                    1079
#define IDC_TYPE1                       1079
#define IDC_QUALITY                     1079
#define IDC_RENAME                      1079
#define IDC_TIMESTAMP                   1080
#define IDC_SLIDE_MOTION                1083
#define IDC_LEVEL_MOTION                1084
#define IDC_MOTIONOVERLAY               1084
#define IDC_SLIDE_BRIGHT                1085
#define IDC_LEVEL_BRIGHT                1086
#define IDC_TEMPLATE                    1086
#define IDC_FINAL                       1087
#define IDC_TXT_FORMAT                  1088
#define IDC_FTPLOG                      1089
#define IDC_OPENFTP                     1090
#define IDC_SMTPLOG                     1091
#define IDC_TXT_SCANTYPE                1091
#define IDC_OPENSMTP                    1092
#define IDC_TXT_MOTION                  1092
#define IDC_TXT_BRIGHT                  1093
#define IDC_EXT                         1096
#define IDC_EXE                         1097
#define IDC_PARAMS                      1099
#define IDC_PROGRESS                    1100
#define IDC_FROM                        1100
#define IDC_CHOOSE_EXE                  1100
#define IDC_FILES                       1101
#define IDC_TO                          1101
#define IDC_HTTP                        1102
#define IDC_FOUNDERED                   1103
#define IDC_PROPERTIES                  1104
#define IDC_THUMBNAIL                   1105
#define IDC_SUBJECT                     1106
#define IDC_PUBLISH1                    1106
#define IDC_CODE                        1107
#define IDC_PUBLISH2                    1107
#define IDC_FRM_NEXT                    1108
#define IDC_PUBLISH3                    1108
#define IDC_FIXEDORDER                  1109
#define IDC_DIR                         1109
#define IDC_REALSIZE                    1110
#define IDC_CHOOSE_DIR                  1110
#define IDC_NOCLIP                      1111
#define IDC_TRAYICON                    1112
#define IDC_DONTASK                     1113
#define IDC_IMGLIST                     1114
#define IDC_AUTOUPDATE                  1114
#define IDC_UPDATE                      1115
#define IDC_NOPREFIX                    1116
#define IDC_SLIDENEGATIVE               1117
#define IDC_MAPTO                       1118
#define IDC_NEGATIVE                    1119
#define IDC_IMAGES                      1120
#define IDC_PANEL                       1120
#define IDC_RTLREADING                  1121
#define IDC_FOLDER                      1122
#define IDC_SINGLELINE                  1123
#define IDC_FTPSERVER                   1123
#define IDC_CHOOSE_FOLDER               1124
#define IDC_PASSWORD                    1125
#define IDC_BOX                         1125
#define IDC_BCK                         1126
#define IDC_TXT_POSITIVE                1126
#define IDC_VIRTUALFOLDER               1127
#define IDC_TXT_NEGATIVE                1127
#define IDC_ADDRESS                     1128
#define IDC_PUBTYPE2                    1128
#define IDC_REMOTE_PASSWORD             1129
#define IDC_HTTPPATH                    1129
#define IDC_PUBTYPE3                    1129
#define IDC_SERVER                      1130
#define IDC_ROOTDIR                     1130
#define IDC_PUBTYPE4                    1130
#define IDC_TTEXT                       1131
#define IDC_CHOOSE_ROOTDIR              1131
#define IDC_PUBTYPE                     1131
#define IDC_REMOTE_PAGE                 1132
#define IDC_PUBTYPE5                    1132
#define IDC_AUTHDETECT                  1133
#define IDC_HTTPPASSWORD                1133
#define IDC_MSG                         1134
#define IDC_USERNAME                    1135
#define IDC_AUTHTYPE                    1136
#define IDC_OVERLAYS                    1136
#define IDC_BACKGROUNDS                 1137
#define IDC_TOOLBAR                     1138
#define IDC_MASKFILE                    1142
#define IDC_CHOOSE_MASKFILE             1143
#define IDC_FTPEDIT                     1149
#define IDC_SETUP                       1151
#define IDC_FTPFILENAME                 1152
#define IDC_TXT_FTPSERVER               1153
#define IDC_TXT_FTPFILENAME             1154
#define IDC_XMAX                        1155
#define IDC_YMAX                        1156
#define IDC_CLOSEICON                   1156
#define IDC_MASKIMG                     1157
#define IDC_SLIDEERR                    1158
#define IDC_SOUNDFILE                   1161
#define IDC_PLAY                        1162
#define IDC_CHOOSE_SOUND                1163
#define IDC_MAXLINES                    1163
#define IDC_SHOWADDR                    1164
#define IDC_SHOWUSERNAME                1165
#define IDC_TXT_MAXLINES                1166
#define IDC_MAXMSGLEN                   1167
#define IDC_WARNING                     1167
#define IDC_TXT_MAXMSGLEN               1168
#define IDC_TXT_HRS                     1168
#define IDC_ALLOWHTML                   1169
#define IDC_TXT_MINS                    1169
#define IDC_TXT_SECONDS                 1170
#define IDC_TXT_HRS2                    1171
#define IDC_TXT_MINS2                   1172
#define IDC_TXT_SECONDS2                1173
#define IDC_TXT_MININT                  1174
#define IDC_URL                         1175
#define IDC_REFRESH                     1176
#define IDC_MSGICON                     1189
#define IDC_TIMEOUT                     1190
#define IDC_FORMATSTR                   1191
#define IDC_PB_FRAMES                   1192
#define IDC_PB_SECONDS                  1193
#define IDC_CAP_FRAMES                  1194
#define IDC_CAP_SECONDS                 1195
#define IDC_FRAMERATE                   1196
#define IDC_SLIDE_FRAMEAVG              1199
#define IDC_SLIDE_PB_SCALE              1200
#define IDC_HTTP_PASSWORD               1201
#define IDC_SLIDE_CAP_SCALE             1201
#define IDC_TREE                        1202
#define IDC_CODEC                       1202
#define IDC_REMAININGTEXT               1203
#define IDC_WINDOW                      1204
#define IDC_ADD                         1205
#define IDC_CAPMOTION                   1205
#define IDC_REMOVE                      1206
#define IDC_TXT_CAPSLOWER               1206
#define IDC_UP                          1207
#define IDC_EDIT                        1207
#define IDC_TXT_CAPFASTER               1207
#define IDC_DOWN                        1208
#define IDC_TXT_CAPFRAMES               1208
#define IDC_EDITITEM                    1209
#define IDC_TXT_CAPSECONDS              1209
#define IDC_FONT                        1210
#define IDC_TXT_CAPPER                  1210
#define IDC_TYPE                        1211
#define IDC_TEXT                        1212
#define IDC_FTP                         1213
#define IDC_FONTSTR                     1214
#define IDC_TYPE2                       1215
#define IDC_TEXTBOX                     1216
#define IDC_EMAIL                       1217
#define IDC_TYPE3                       1218
#define IDC_PRINT                       1218
#define IDC_FILE                        1219
#define IDC_STATUS                      1220
#define IDC_COLORBOX                    1221
#define IDC_EXPANDTABS                  1222
#define IDC_MASKCOLOR                   1222
#define IDC_CHOOSE_FILE                 1223
#define IDC_VALUE                       1224
#define IDC_EXTERNALLEADING             1225
#define IDC_SENDEMAIL                   1225
#define IDC_STARTINDEX                  1226
#define IDC_ESCAPEMENT                  1227
#define IDC_REGSTRING                   1228
#define IDC_STOPINDEX                   1229
#define IDC_WHEN                        1230
#define IDC_FONTWIDTH                   1231
#define IDC_CURRENTINDEX                1232
#define IDC_WHEN2                       1233
#define IDC_SHADOW                      1234
#define IDC_EDITCONTROL                 1235
#define IDC_END_ELLIPSIS                1236
#define IDC_PATH_ELLIPSIS               1237
#define IDC_HALIGN                      1238
#define IDC_PWIDTH                      1239
#define IDC_VALIGN                      1240
#define IDC_TNSIZING                    1241
#define IDC_WORDBREAK                   1242
#define IDC_PHEIGHT                     1243
#define IDC_MULTICENTER                 1244
#define IDC_TNSIZING2                   1245
#define IDC_ESCAPEMENTCENTER            1246
#define IDC_RATIO                       1247
#define IDC_ACTION                      1248
#define IDC_ACTION2                     1249
#define IDC_ACTION3                     1250
#define IDC_CHARMAP                     1251
#define IDC_EFFECTS                     1252
#define IDC_SLIDER                      1253
#define IDC_DESC                        1254
#define IDC_BOOL                        1255
#define IDC_REMOVEALL                   1256
#define IDC_HOUR                        1257
#define IDC_MIN                         1258
#define IDC_SEC                         1259
#define IDC_IMG                         1260
#define IDC_HOUR2                       1260
#define IDC_MIN2                        1261
#define IDC_SEC2                        1262
#define IDC_MV_ICON                     3472
#define IDC_MV_CLEAR                    3503
#define IDC_MV_SAVE                     3506
#define ID_CONNECT                      32772
#define ID_ENABLEPUBLISHING             32772
#define ID_IMGLIST_FROMCLIPBOARD        32772
#define ID_IMGLIST_DELETEIMAGE          32773
#define ID_INSERTTEXT                   32774
#define ID_EFFECTS_FLIPHORIZONTALLY     32774
#define ID_INSERTTIME                   32775
#define ID_EFFECTS_FLIPVERTICALLY       32775
#define ID_INSERTDATE                   32776
#define ID_EFFECTS_ROTATERIGHT          32776
#define ID_EFFECTS_ROTATELEFT           32777
#define ID_EFFECTS_GRAYSCALE            32778
#define ID_EFFECTS_NEGATIVE             32779
#define ID_INSERTIMAGE                  32780
#define ID_EFFECTS_LIGHTEN              32780
#define ID_TRAYICON_EXIT                32781
#define ID_EFFECTS_DARKEN               32781
#define ID_INSERTRECT                   32782
#define ID_TRAYICON_ENABLEPUBLISHING    32783
#define ID_INSERTWATERMARK              32784
#define ID_INSERTLINK                   32785
#define ID_INSERTVIDEO                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define ID_SAVEIMAGE                    32789
#define ID_BUTTON32791                  32791
#define ID_INSERTURL                    32792
#define ID_OPTIONS_SETUPWIZARD          32794
#define ID_POPUP_COPY                   32795
#define ID_OPTIONS_SETTINGS             32796
#define ID_POPUP_CUT                    32797
#define CG_ID_VIEW_SERVER               32798
#define ID_VIEW_WEBSERVER               32798
#define ID_POPUP_PASTE                  32799
#define CG_ID_VIEW_INSERT               32800
#define ID_POPUP_PROPERTIES             32801
#define ID_NEWIMAGE                     32802
#define ID_POPUP_DELETE                 32803
#define ID_DELETEIMAGE                  32804
#define ID_POPUP_DUPLICATE              32805
#define ID_BUTTON32803                  32806
#define ID_REFRESH                      32806
#define ID_INSERTSCREENSHOT             32807
#define ID_INSERTSTEXT                  32808
#define ID_OPTIONS_CHECKFORUPDATE       32809
#define ID_EDIT_PROPERTIES              32810
#define ID_VIEW_OVERLAYBAR              32811
#define ID_VIEW_PROPERTIES              32812
#define ID_OPTIONS_HTMLBUILDER          32813
#define ID_VIEW_PUBIMGVIEW              32815
#define ID_FILE_LOADOVERLAY             32820
#define ID_FILE_SAVEOVERLAY             32821
#define ID_FILE_MERGEOVERLAY            32822
#define ID_IMAGELIST_NEWIMAGE           32823
#define ID_TRAYICON_ABOUT               32824
#define ID_IMAGELIST_DELETEIMAGE        32824
#define ID_IMAGELIST_PROPERTIES         32825
#define ID_SIMPLE                       32826
#define ID_SETUPSIMPLE                  32827
#define ID_VIEW_EVENTLOG                32828
#define ID_HELP_HELP                    32829
#define ID_VIEW_GRAPHBAR                32830
#define ID_IMAGELIST_VIEW               32831
#define ID_VIEWIMAGE                    32832
#define ID_TRAYICON_EMAILIMAGE          32837
#define IDP_OLE_INIT_FAILED             32838
#define ID_HELP_REGISTRATION            32839
#define IDC_TIPFRAME                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        307
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1211
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
